<?php

namespace AppBundle\Repository;

/**
 * AccessAdminCommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessAdminCommunityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUnic()
    {
        $qb = $this->createQueryBuilder('a')
                 ->groupBy('a.access');
        return $qb;
    }
}
