<?php

namespace AppBundle\Repository;


/**
 * AdminAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminAccessRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Community $community
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllAccesses($community)
    {
        $qb = $this->createQueryBuilder('ac');
        if(!$community->hasSetting('activate_usefulllinks')) {
            $qb->where('ac.slug != :slug1')->setParameter('slug1','usefull_links_create');
        }

        if(!$community->hasSetting('activate_survey')) {
            $qb->andWhere('ac.slug != :slug2')->setParameter('slug2','survey_create');
        }

        return $qb;
    }

    public function findAllPublicAccesses($community)
    {
        $qb = $this->createQueryBuilder('ac');
        $qb->where('ac.isPrivate = :isPrivate')->setParameter('isPrivate',false);
        if(!$community->hasSetting('activate_usefulllinks')) {
            $qb->andWhere('ac.slug != :slug1')->setParameter('slug1','usefull_links_create');
        }

        if(!$community->hasSetting('activate_survey')) {
            $qb->andWhere('ac.slug != :slug2')->setParameter('slug2','survey_create');
        }

        return $qb;
    }
}
