<?php

namespace AppBundle\Repository;

/**
 * AssociationDeletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationDeletedRepository extends \Doctrine\ORM\EntityRepository
{
}
