<?php

namespace AppBundle\Repository;

/**
 * CarpoolingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEventCarpool($event)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id', 'c.meetingTime', 'c.nbPlaces', 'c.phoneNumber', 'c.relayPoint')
            ->andWhere('c.event = :event')->setParameter('event', $event);
        return $qb->getQuery()->getResult();

    }
}
