<?php

namespace AppBundle\Repository;

/**
 * CarpoolingAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
