<?php

namespace AppBundle\Repository;

/**
 * CategoryPhoneBookHeadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryPhoneBookHeadingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLocalActorByHeading($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.phoneBookHeading = :phoneBookHeading')->setParameter('phoneBookHeading', $id);
        return $qb->getQuery()->getResult();

    }
}
