<?php

namespace AppBundle\Repository;

/**
 * CommunityUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
