<?php

namespace AppBundle\Repository;

/**
 * CommunityPasswordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityPasswordsRepository extends \Doctrine\ORM\EntityRepository
{
}
