<?php

namespace AppBundle\Repository;

/**
 * DeviceTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
