<?php

namespace AppBundle\Repository;

/**
 * DuplicateEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuplicateEventRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNextByDate(
        $minDate,
        $duplicateEventId
    )
    {
        $qb = $this ->createQueryBuilder('duplicateEvent')
                    ->select('duplicateEvent')
                    ->Where('duplicateEvent.createAt >= :minDate')
                    ->andWhere('duplicateEvent.idParent = :duplicateEventId');
                    
        $qb->setParameters(
            array(
                "minDate"           =>  $minDate,
                "duplicateEventId"  =>  $duplicateEventId
                )
        );
        return $qb->getQuery()->getResult();
    }
}
