<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventVolunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventVolunteerRepository extends EntityRepository
{
    public function findVolunteers($type, $account)
    {
        $qb = $this->createQueryBuilder('e');
        $qb ->join('e.event', 'v')
            ->join('e.user','u');
        if ($type == 'association') {
            $qb ->join('v.association', 'a')
                ->where('a.id = :id');
        } else {
            $qb ->join('v.community', 'c')
                ->where('c.id = :id');
                /*->andWhere('e.type = :commuType')
                ->setParameter('commuType', '%community%');*/
        }
        $qb->select('u.firstname','u.lastname','u.email','e.value','e.id','v.title')
            ->setParameter('id', $account->getId());

        return $qb->getQuery()->getResult();
    }
}
