<?php

namespace AppBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDocsMoreThanThreeMonths()
    {
        $date = new \DateTime();
        $date->modify('-3 month');
        $qb = $this->createQueryBuilder('n');


        $qb->where('n.fileUpdatedAt < :date')->setParameter('date',$date);
        $qb->andWhere('n.type like :type')->setParameter('type','application/%');
        return $qb->getQuery()->getResult();
    }
}
