<?php

namespace AppBundle\Repository;

/**
 * MailChimpSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailChimpSubscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
