<?php

namespace AppBundle\Repository;

/**
 * MerchantDeletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantDeletedRepository extends \Doctrine\ORM\EntityRepository
{
}
