<?php

namespace AppBundle\Repository;

/**
 * MerchantUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantUserRepository extends \Doctrine\ORM\EntityRepository
{
}
