<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Merchant;
use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * MerchantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantRepository extends EntityRepository
{
    public function count($cityhall = null, $dateBefore = null, $dateAfter = null, $name = null, $enabled = null, $moderate = null, $wait = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('COUNT(c)');
        if ($cityhall) {
            $qb->andWhere('c.community = :cityhall')->setParameter('cityhall', $cityhall);
        }
        if ($dateBefore) {
            $dateBefore = substr($dateBefore, 6, 4) . '-' . substr($dateBefore, 3, 2) . '-' . substr($dateBefore, 0, 2) . ' ' . substr($dateBefore, 11, 8);
            $qb->andwhere('c.createAt >= :dateBefore')->setParameter('dateBefore', $dateBefore);
        }
        if ($dateAfter) {
            $dateAfter = substr($dateAfter, 6, 4) . '-' . substr($dateAfter, 3, 2) . '-' . substr($dateAfter, 0, 2) . ' ' . substr($dateAfter, 11, 8);
            $qb->andWhere('c.createAt <= :dateAfter')->setParameter('dateAfter', $dateAfter);
        }
        if ($name) {
            $qb->andWhere('c.name LIKE :name')->setParameter('name', '%' . $name . '%');
        }
        if ($enabled != '' && $enabled != null) {
            $qb->andWhere('c.enabled = :enabled')->setParameter('enabled', $enabled);
        }
        if ($wait != '' && $wait == 'true') {
            $qb->andWhere('c.moderate = :moderate')->setParameter('moderate', 'wait');
        } else {
            if ($moderate != '' && $moderate != null) {
                $qb->andWhere('c.moderate = :moderate')->setParameter('moderate', $moderate);
            }
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param $page
     * @param $order
     * @param $cityhall
     * @param $dateBefore
     * @param $dateAfter
     * @param $name
     * @param $enabled
     * @param $moderate
     * @param $wait
     * @param int $limit
     * @param null $categories
     * @return Merchant[]
     */
    public function search($page, $order, $cityhall, $dateBefore, $dateAfter, $name, $enabled, $moderate, $wait, $limit = 25, $categories = null)
    {
        $qb = $this->createQueryBuilder('c');
        if ($cityhall) {
            $qb->andWhere('c.community = :cityhall')->setParameter('cityhall', $cityhall);
        }
        if ($dateBefore) {
            $dateBefore = substr($dateBefore, 6, 4) . '-' . substr($dateBefore, 3, 2) . '-' . substr($dateBefore, 0, 2) . ' ' . substr($dateBefore, 11, 8);
            $qb->andwhere('c.createAt >= :dateBefore')->setParameter('dateBefore', $dateBefore);
        }
        if ($dateAfter) {
            $dateAfter = substr($dateAfter, 6, 4) . '-' . substr($dateAfter, 3, 2) . '-' . substr($dateAfter, 0, 2) . ' ' . substr($dateAfter, 11, 8);
            $qb->andWhere('c.createAt <= :dateAfter')->setParameter('dateAfter', $dateAfter);
        }
        if ($name) {
            $qb->andWhere('c.name LIKE :name')->setParameter('name', '%' . $name . '%');
        }
        if ($enabled != '' && $enabled != null) {
            $qb->andWhere('c.enabled = :enabled')->setParameter('enabled', $enabled);
        }
        if ($wait != '' && $wait == 'true') {
            $qb->andWhere('c.moderate = :moderate')->setParameter('moderate', 'wait');
        } else {
            if ($moderate != '' && $moderate != null) {
                $qb->andWhere('c.moderate = :moderate')->setParameter('moderate', $moderate);
            }
        }

        if ($categories) {
            $qb->where('c.category IN (:categories)')->setParameter('categories', $categories);
        }

        if (is_array($order)) {
            foreach ($order as $orderName => $orderType) {
                $qb->orderBy('c.' . $orderName, $orderType);
            }
        }
        if ($page !== false) {
            $qb->setMaxResults($limit)
                    ->setFirstResult($page * $limit);
        }

        return $qb->getQuery()->getResult();
    }

    public function findAllByCommunity($community)
    {
        $qb = $this->createQueryBuilder('u');
        if ($community != '') {
            $qb->andWhere('u.community = :communty')->setParameter('communty', $community);
            $qb->andWhere('u.moderate = :moderate')->setParameter('moderate', 'accepted');
        }
        return $qb;
    }

    public function findUserMerchants($user)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->andWhere('c.suAdmin = :user OR :user MEMBER OF c.admins')->setParameter('user', $user)
                ->andWhere('c.enabled = :enabled')->setParameter('enabled', true)
                ->andWhere('c.moderate = :accepted OR c.moderate = :wait')->setParameter('accepted', 'accepted')->setParameter('wait', 'wait');

        return $qb->getQuery()->getResult();
    }

    public function findAllByCities($user)
    {
        $cities = $user->getCitiesIds();
        $qb = $this->createQueryBuilder('m');
        $qb->join("m.city", "ac");
        $qb->where("ac.id IN (:cities)")->setParameter("cities", $cities);
        $qb->orderBy('m.name');
        return $qb->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @param $key
     * @param $theme
     * @param $city
     * @return array
     *
     */
    public function appSearch($user, $key, $theme, $city)
    {
        if ($city == "all") {
            $cities = $user->getCommunities();
        } else {
            $cities = $city;
        }

        $comm = [];

        foreach ($cities as $city) {
            if($city->getType() == 'approved'){
                $comm[]=$city->getCommunity();
            }

        }

        $qb = $this->createQueryBuilder('m')
            ->select("m.id, m.name")
            ->leftJoin('m.image', 'img')
            ->addSelect("img.id As image")
            ->where("m.community IN (:cities)")
            ->setParameter('cities', $comm)
            ->andWhere('m.enabled = :enabled')->setParameter('enabled', true)
            ->andWhere('m.moderate = :accepted OR m.moderate = :wait')->setParameter('accepted', 'accepted')->setParameter('wait', 'wait');

        if ($key) {
            $qb->andWhere("m.name LIKE :name")
                    ->setParameter("name", '%' . $key . '%');
        }

        if ($theme) {
            $qb->andWhere("m.category = :category")
                    ->setParameter("category", $theme);
        }

        return $qb->getQuery()->getResult();
    }

    public function findBySuAdmin($user)
    {
        $qb = $this->createQueryBuilder('m')
                ->select("m.id, m.name")
                ->leftJoin('m.image', 'img')
                ->addSelect("img.id As image")
                ->join("m.suAdmin", "u")
                ->where("u.id = :user")
                ->setParameter("user", $user->getId());
        return $qb->getQuery()->getResult();
    }

    /**
     * @param User $user
     * @return Merchant[]
     */
    public function getJoinedMerchant($user)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->join("m.users", "u")
            ->andWhere('u.user = :user')->setParameter('user', $user)
            ->andWhere('u.type = :status')->setParameter('status', 'approved')
            ->andWhere('m.enabled = :enabled')->setParameter('enabled', true)
            ->andWhere('m.moderate = :accepted ')->setParameter('accepted', 'accepted');

        return $qb->getQuery()->getResult();
    }

    public function getMembershipDemands($association)
    {
        $qb = $this->createQueryBuilder('a')
            ->select("a.id, a.name")
            ->leftJoin('a.users', 'demand')

            ->leftJoin('demand.user','u')
            ->addSelect("u.id As user_id, u.firstname as firstname, u.lastname as lastname, u.email as email")
            ->leftJoin('u.image','img')
            ->addSelect('img.filename as userImg')
            ->where('demand.merchant = :asso')->setParameter('asso',$association)
            ->andWhere('demand.type = :type')->setParameter('type','pending');
        return $qb->getQuery()->getResult();
    }

    public function getMemberships($association)
    {
        $qb = $this->createQueryBuilder('a')
            ->select("a.id, a.name")
            ->leftJoin('a.users', 'demand')

            ->leftJoin('demand.user','u')
            ->addSelect("u.id As user_id, u.firstname as firstname, u.lastname as lastname, u.email as email")
            ->leftJoin('u.image','img')
            ->addSelect('img.filename as userImg')
            ->where('demand.merchant = :asso')->setParameter('asso',$association)
            ->andWhere('demand.type = :type')->setParameter('type','approved');
        return $qb->getQuery()->getResult();
    }
    public function formatMerchant($merchant,$role)
    {
        $merch = array(
            "id" => $merchant->getId(),
            "createAt" => $merchant->getCreateAt(),
            "name" => $merchant->getName(),
            "address" => $merchant->getAddress(),
            "codePostal" => $merchant->getCodePostal(),
            "description" => $merchant->getDescription(),
            "category" => array(
                "id" => $merchant->getCategory()->getId(),
                "name" => $merchant->getCategory()->getName(),
                "type" => $merchant->getCategory()->getType(),
            ),
            "email" => $merchant->getEmail(),
            "phone" => $merchant->getPhone(),
            "siret" => $merchant->getSiret(),
            "moderate" => $merchant->getModerate(),
            "role" => $role,
            "timing" => $merchant->getTiming(),
            "image_url" => $merchant->getImageUrl(),
            "community" => array(
                "id" => $merchant->getCommunity()->getId(),
                "categories" => $merchant->getCommunity()->getCategories()),
            "city" => array(
                "id" => $merchant->getCity()->getId(),
                "name" => $merchant->getCity()->getName(),
                'code' => $merchant->getCity()->getZipcode()),
            "type" => 'merchant'
        );

        return $merch;
    }
}
