<?php

namespace AppBundle\Repository;

/**
 * NavigationLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationLogRepository extends \Doctrine\ORM\EntityRepository
{
}
