<?php

namespace AppBundle\Repository;

/**
 * SurveyQuestionChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionChoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChoiceSurvey($question)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.id','s.title')
            ->andWhere('s.question = :question')->setParameter('question', $question);

        return $qb->getQuery()->getResult();
    }
}
