<?php

namespace AppBundle\Repository;

/**
 * SurveyQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyQuestionRepository extends \Doctrine\ORM\EntityRepository
{

    public function countResponses($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('COUNT(c)');
        $qb->innerJoin('c.choices', 'cc');
        $qb->innerJoin('cc.responses', 'cr');
        $qb->where('c.id = :id')->setParameter('id', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getQuestionsSurveys($survey)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.id','s.title')
            ->andWhere('s.survey = :survey')->setParameter('survey', $survey);
        return $qb->getQuery()->getResult();
    }

}
