<?php

namespace AppBundle\Repository;

/**
 * volunteerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class volunteerRepository extends \Doctrine\ORM\EntityRepository
{
}
