api_v1:
    type:     rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
 
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    

    
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_user:
    type:     rest
    resource: "@ApiBundle/Resources/config/routing/user.yml"
