<?php

namespace UserBundle\Repository;

/**
 * UserDeletedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDeletedRepository extends \Doctrine\ORM\EntityRepository
{
}
